server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.125.89.224:3308/word_book?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Caonima3344
  data:
    redis:
      host: 112.125.89.224
      port: 6379
      password: caonima3344
  ai:
    openai:
      api-key: sk-QVy3doHm7g5tVPZt51Cd5882279c41C1Be67C780C4974886
      base-url: https://shitongxue.cn
      chat:
        options:
          model: gpt-3.5-turbo
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.serein.wordbook.entity
